"""AssetStore — content-addressed local filesystem storage for raw and
derived binaries. §02/§11: local filesystem now, behind an interface that
swaps to S3/MinIO later without touching any caller. Never store binaries
in MongoDB documents (§06 document-size discipline).
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import BinaryIO, Protocol

from omnitrace.config import get_settings
from omnitrace.ids import sha256_file


class AssetStore(Protocol):
    def put_file(self, src_path: str, *, source_id: str, kind: str, filename: str) -> str: ...
    def put_stream(self, stream: BinaryIO, *, source_id: str, kind: str, filename: str) -> str: ...
    def resolve(self, storage_path: str) -> Path: ...


class LocalAssetStore:
    """Layout: {asset_root}/{kind}/{source_id}/{filename}

    `kind` is "raw" for original uploads and "derived" for anything a
    processor produces (frames, page images, cropped OCR regions, extracted
    audio). Keeping raw and derived physically separate makes it obvious at
    a glance which files are immutable ground truth and which can be
    regenerated by re-running a stage.
    """

    def __init__(self, root: str | None = None) -> None:
        self.root = Path(root or get_settings().asset_root)
        self.root.mkdir(parents=True, exist_ok=True)

    def _dest(self, *, source_id: str, kind: str, filename: str) -> Path:
        d = self.root / kind / source_id
        d.mkdir(parents=True, exist_ok=True)
        return d / filename

    def put_file(self, src_path: str, *, source_id: str, kind: str, filename: str) -> str:
        dest = self._dest(source_id=source_id, kind=kind, filename=filename)
        shutil.copyfile(src_path, dest)
        return str(dest.relative_to(self.root))

    def put_stream(self, stream: BinaryIO, *, source_id: str, kind: str, filename: str) -> str:
        dest = self._dest(source_id=source_id, kind=kind, filename=filename)
        with open(dest, "wb") as out:
            shutil.copyfileobj(stream, out)
        return str(dest.relative_to(self.root))

    def resolve(self, storage_path: str) -> Path:
        """Resolve a stored relative path back to an absolute filesystem path.
        Guards against path traversal — a storage_path is always relative to
        the asset root and must stay inside it."""
        resolved = (self.root / storage_path).resolve()
        if not resolved.is_relative_to(self.root.resolve()):
            raise ValueError(f"storage_path escapes asset root: {storage_path!r}")
        return resolved

    def hash_of(self, storage_path: str) -> str:
        return sha256_file(str(self.resolve(storage_path)))


_store: LocalAssetStore | None = None


def get_asset_store() -> LocalAssetStore:
    global _store
    if _store is None:
        _store = LocalAssetStore()
    return _store
